set_buzzer_on:
  description: Turns humidifier buzzer on.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "humidifier.bedroom"

set_buzzer_off:
  description: Turns humidifier buzzer off.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "humidifier.bedroom"

set_led_on:
  description: Turns humidifier LED on.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "humidifier.bedroom"

set_led_off:
  description: Turns humidifier LED off.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "humidifier.bedroom"
